### ISSUE TITLE
2) Copiar archivos .gitignore y platformio.ini en carpeta Software.

### ISSUE THREAD

**Issue by alfredop37** [ISPC-TST-CONTROL-Y-SERVICIOS/proyecto-final-grupo2#5]
Copiar los siguientes archivos:

- .gitignore
- platformio.ini

 en el  path:
https://github.com/ISPC-TST-CONTROL-Y-SERVICIOS/proyecto-final-grupo2/tree/main/ControladorMx/Desarrollo/SRC/Implementacion/Software

**Comment by guelo2019** [comment]
Se subieron archivos .gitignore y platformio.ini a carpeta indicada
